name: Manual Copy All from Repo A

on:
  workflow_dispatch:

jobs:
  copy-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v3

    - name: Clone Repo A (carsrus-marketplace-maurituis)
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git clone https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/rishenarmoogum/carsrus-marketplace-maurituis.git temp-repo-a

    - name: Copy all files from Repo A to Repo B
      run: |
        rsync -av --progress temp-repo-a/ ./ --exclude .git

    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Manual sync from Repo A (full copy)" || echo "Nothing to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/rishenarmoogum/CarsRus_app.git HEAD:main



