name: Manual Copy All from Repo A

on:
  workflow_dispatch:

jobs:
  copy-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v3

    - name: Clone Repo A
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git clone https://$REPO_ACCESS_TOKEN@github.com/rishenarmoogum/carsrus-marketplace-maurituis.git temp-repo-a

    - name: Copy all files from Repo A to Repo B
      run: |
        # Copy everything except .git directory
        rsync -av --progress temp-repo-a/ ./ --exclude .git

    - name: Commit and push
      run: |
        git add .
        git commit -m "Manual sync from Repo A (full copy)"
        git push origin main


